version: '3'
services:
  platform_repo:
    build: ../platformRepo
    container_name: platform_repo
    volumes:
      - platform_repo:/sharedFiles
  platform:
    build: .
    hostname: 'keellis1.kellis5137.com'
    volumes:
      - "appdInstallDir:/opt/appdynamics:nocopy"
      - "platform_repo:/sharedFiles"
    extra_hosts:
      - "platform1-docker:192.168.68.136"
    ports:
      - "8090:8090"
      - "8181:8181"
      - "9191:9191"
      - "7001:7001"
      - "7002:7002"
    ulimits:
      nofile:
        soft: "65535"
        hard: "65535"
      nproc:
        soft: "8192"
        hard: "8192"
# Might need to set swappiness to 10, BUT I'm not sure exactly the requirements
# The problem: v3 of compose doesn't appear to allow it to be set. However,
# v2 does, but also wondering if there is another way or needed. TODO
volumes:
  appdInstallDir:
  platform_repo:
