#FROM centos:centos7
#FROM registry.access.redhat.com/ubi7/ubi
FROM ../base-rhel7ubi

MAINTAINER Keith Ellis (keith.ellis@appdynamics.com)

# Install packages
#RUN yum install -y --disableplugin=subscription-manager https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
# RUN yum install -y --disableplugin=subscription-manager epel-release

